apiVersion: v1
kind: Config
clusters:
- name: ${cluster_name}
  cluster:
    certificate-authority-data: ${ca}
    server: ${server}
contexts:
- name: ${context_name}
  context:
    cluster: ${cluster_name}
    namespace: ${namespace}
    user: ${user_name}
users:
- name: ${user_name}
  user:
    token: ${token}
